apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: himedia-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.8.240-10.10.8.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: himedia-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - himedia-pool
